# Generated by Django 5.0.4 on 2024-05-11 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_alter_resume_address_alter_resume_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="job_title",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="professional_summary",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
