# Generated by Django 5.0.4 on 2024-05-11 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_resume_job_title_resume_professional_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="github",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="linkedin",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
