# Generated by Django 5.0.4 on 2024-05-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_resume_github_resume_linkedin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
    ]
